pipeline
    {
    agent any

    stages
        {
        stage('Setup "Environment')
            {
            steps
                {
                sh 'echo "Setting up environment..."'
                //Установка зависимостей, если это необходимо
                }
            }
        stage('Data creation')
            {
            steps
                {
                sh 'python3 HW_2/data_creation.py'
                }
            }
        stage('Preprocess Data')
            {
            steps
                {
                sh 'python3 HW_2/model_preprocessing.py'
                }
            }
        stage('Preparation Model')
            {
            steps
                {
                sh 'python3 HW_2/model_preparation.py'
                }
            }
//         stage('Train Model')
//             {
//             steps
//                 {
//                 sh 'python3 scripts/train_model.py'
//                 }
//             }
        }
        post
            {
            alweys
                {
                sh 'echo "Pipline completed."'
                }
            }
    }